server:
  port: 8093
mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.analysys.blog.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    username: analysys_club
    password: YiGuanXYZ.@()85258638
    url: jdbc:mysql://118.25.133.235:3306/yiguan?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

#  # 静态资源路径
#  resources:
#    static-locations: classpath:static/,file:static/
logging:
  level:
    com.analysys.repository: DEBUG
  file:
    logs/application.log
