package com.analysys.blog.entity;

public class ArticleTagKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.article_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column article_tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    private Integer tagId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.article_id
     *
     * @return the value of article_tag.article_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.article_id
     *
     * @param articleId the value for article_tag.article_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column article_tag.tag_id
     *
     * @return the value of article_tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column article_tag.tag_id
     *
     * @param tagId the value for article_tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }
}