package com.analysys.blog.entity;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    private Integer tagId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.tag_name
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    private String tagName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.call_num
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    private Integer callNum;

    private String size;

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_id
     *
     * @return the value of tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public Integer getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_id
     *
     * @param tagId the value for tag.tag_id
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.tag_name
     *
     * @return the value of tag.tag_name
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public String getTagName() {
        return tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.tag_name
     *
     * @param tagName the value for tag.tag_name
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public void setTagName(String tagName) {
        this.tagName = tagName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.call_num
     *
     * @return the value of tag.call_num
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public Integer getCallNum() {
        return callNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.call_num
     *
     * @param callNum the value for tag.call_num
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    public void setCallNum(Integer callNum) {
        this.callNum = callNum;
    }
}