package com.analysys.blog.repository;

import com.analysys.blog.entity.ArticleTagKey;
import com.analysys.blog.entity.Tag;

import java.util.List;

public interface ArticleTagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int deleteByPrimaryKey(ArticleTagKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int insert(ArticleTagKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table article_tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int insertSelective(ArticleTagKey record);



}