package com.analysys.blog.repository;

import com.analysys.blog.entity.Tag;

import java.util.List;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int deleteByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    Tag selectByPrimaryKey(Integer tagId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sun May 26 17:07:11 CST 2019
     */
    int updateByPrimaryKey(Tag record);


    /**
     * 根据文章id获取, 获取完整文章内容时要用到
     *
     * @param
     * @return
     */
    List<Tag> selectTagByArticleId(Integer articleId);


    List<Tag> selectPopularTagWithLimitNum(Integer defaultFetchNumOfPopularTag);
    
    
    /**
     * 增加标签点击数
     *
     * @param
     * @return 
     */
    int addOneToCallNumByTagId(Integer tagId);
}